# Generated by Django 4.0.3 on 2022-05-19 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_remove_food_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
