spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: mysql
    url: jdbc:mysql:///client?cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&ipTypes=PRIVATE&zeroDateTimeBehavior=convertToNull&user=root&password=
    username: root
    maximumPoolSize: 5
  log-properties: true
cors:
  max-age: 3600
  allowed-origin: https://for-developers-343319.ey.r.appspot.com
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/hackhathon?zeroDateTimeBehavior=convertToNull
    username: root
    password: password
    maximumPoolSize: 5
    minimumIdle: 5
  log-properties: false
cors:
  max-age: 3600
  allowed-origin: http://localhost:4200

management:
  info:
    git:
      mode: full
