runtime: java11
instance_class: B2
vpc_access_connector:
  name: "projects/for-developers-343319/locations/europe-west3/connectors/vpc-connector"
basic_scaling:
  max_instances: 1
  idle_timeout: 30m
env_variables:
  SPRING_PROFILES_ACTIVE: prod
  CLOUD_SQL_CONNECTION_NAME: for-developers-343319:europe-west3:hackhathon
  SERVER_PORT: 8080
